/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

#include <refos-rpc/rpc.h>
#include <refos-rpc/data_server.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>

#include <sys/types.h>

#include <stdint.h>
#include <stdlib.h>

/*! @file
    @brief Generated file for the data interface. Please do NOT edit this file. */

void server_data_open(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    char* rpc_name = (char*)rpc_sv_pop_str(rpc_userptr);
    int rpc_flags = (int)rpc_sv_pop_uint(rpc_userptr);
    int rpc_mode = (int)rpc_sv_pop_uint(rpc_userptr);
    int rpc_size = (int)rpc_sv_pop_uint(rpc_userptr);
    int* rpc_errval = rpc_malloc(sizeof(int));
    seL4_CPtr rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_name);
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = data_open_handler(rpc_userptr, rpc_name, rpc_flags, rpc_mode, rpc_size, rpc_errval);

    reply_data_open(rpc_userptr, rpc_errval, rpc___ret__);
}

void reply_data_open(void *rpc_userptr, int* rpc_errval, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(int));
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_close(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_close_handler(rpc_userptr, rpc_dspace_fd);

    reply_data_close(rpc_userptr, *rpc___ret__);
}

void reply_data_close(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_read(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_offset = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    uint32_t rpc_count = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    rpc_buffer_t rpc_buf;
    rpc_buf.data = rpc_malloc(rpc_count * sizeof(byte));
    rpc_buf.count = rpc_count;
    int rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_buf.data);


    rpc___ret__ = data_read_handler(rpc_userptr, rpc_dspace_fd, rpc_offset, rpc_buf, rpc_count);

    reply_data_read(rpc_userptr, rpc_buf, rpc___ret__);
}

void reply_data_read(void *rpc_userptr, rpc_buffer_t rpc_buf, int rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf_array(rpc_userptr, rpc_buf, sizeof(byte));
    rpc_sv_push_uint(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_write(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_offset = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    rpc_buffer_t rpc_buf = (rpc_buffer_t)rpc_sv_pop_buf_array(rpc_userptr, sizeof(byte));
    uint32_t rpc_count = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    int rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_buf.data);


    rpc___ret__ = data_write_handler(rpc_userptr, rpc_dspace_fd, rpc_offset, rpc_buf, rpc_count);

    reply_data_write(rpc_userptr, rpc___ret__);
}

void reply_data_write(void *rpc_userptr, int rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_uint(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_getc(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    int rpc_block = (int)rpc_sv_pop_uint(rpc_userptr);
    int rpc___ret__ = 0;


    rpc___ret__ = data_getc_handler(rpc_userptr, rpc_dspace_fd, rpc_block);

    reply_data_getc(rpc_userptr, rpc___ret__);
}

void reply_data_getc(void *rpc_userptr, int rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_uint(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_putc(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    int rpc_c = (int)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_putc_handler(rpc_userptr, rpc_dspace_fd, rpc_c);

    reply_data_putc(rpc_userptr, *rpc___ret__);
}

void reply_data_putc(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_lseek(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    off_t* rpc_offset = rpc_malloc(sizeof(off_t));
    rpc_sv_pop_buf(rpc_userptr, rpc_offset, sizeof(off_t));
    int rpc_whence = (int)rpc_sv_pop_uint(rpc_userptr);
    off_t* rpc___ret__ = rpc_malloc(sizeof(off_t));

    rpc_sv_track_obj(rpc_userptr, rpc_offset);

    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_lseek_handler(rpc_userptr, rpc_dspace_fd, *rpc_offset, rpc_whence);

    reply_data_lseek(rpc_userptr, *rpc___ret__);
}

void reply_data_lseek(void *rpc_userptr, off_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(off_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_get_size(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc___ret__ = 0;


    rpc___ret__ = data_get_size_handler(rpc_userptr, rpc_dspace_fd);

    reply_data_get_size(rpc_userptr, rpc___ret__);
}

void reply_data_get_size(void *rpc_userptr, uint32_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_uint(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_expand(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_size = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_expand_handler(rpc_userptr, rpc_dspace_fd, rpc_size);

    reply_data_expand(rpc_userptr, *rpc___ret__);
}

void reply_data_expand(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_datamap(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    seL4_CPtr rpc_memoryWindow = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_offset = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_datamap_handler(rpc_userptr, rpc_dspace_fd, rpc_memoryWindow, rpc_offset);

    reply_data_datamap(rpc_userptr, *rpc___ret__);
}

void reply_data_datamap(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_dataunmap(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_memoryWindow = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_dataunmap_handler(rpc_userptr, rpc_memoryWindow);

    reply_data_dataunmap(rpc_userptr, *rpc___ret__);
}

void reply_data_dataunmap(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_init_data(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_destDataspace = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    seL4_CPtr rpc_srcDataspace = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_srcDataspaceOffset = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_init_data_handler(rpc_userptr, rpc_destDataspace, rpc_srcDataspace, rpc_srcDataspaceOffset);

    reply_data_init_data(rpc_userptr, *rpc___ret__);
}

void reply_data_init_data(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_have_data(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    seL4_CPtr rpc_faultNotifyEP = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t* rpc_dataID = rpc_malloc(sizeof(uint32_t));
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));

    rpc_sv_track_obj(rpc_userptr, rpc_dataID);

    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_have_data_handler(rpc_userptr, rpc_dspace_fd, rpc_faultNotifyEP, rpc_dataID);

    reply_data_have_data(rpc_userptr, rpc_dataID, *rpc___ret__);
}

void reply_data_have_data(void *rpc_userptr, uint32_t* rpc_dataID, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_dataID, sizeof(uint32_t));
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_unhave_data(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_unhave_data_handler(rpc_userptr, rpc_dspace_fd);

    reply_data_unhave_data(rpc_userptr, *rpc___ret__);
}

void reply_data_unhave_data(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_data_provide_data_from_parambuffer(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dspace_fd = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_offset = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    uint32_t rpc_contentSize = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = data_provide_data_from_parambuffer_handler(rpc_userptr, rpc_dspace_fd, rpc_offset, rpc_contentSize);

    reply_data_provide_data_from_parambuffer(rpc_userptr, *rpc___ret__);
}

void reply_data_provide_data_from_parambuffer(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}


