/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

// DO NOT EDIT MANUALLY!!!
// This file was generated by CIDL - Simple C IDL Compiler.

#include <refos-rpc/rpc.h>
#include <refos-rpc/data_server.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>

#include <sys/types.h>


int rpc_sv_data_dispatcher(void *rpc_userptr, uint32_t label) {
    switch (label) {
        case RPC_DATA_OPEN:
            assert(data_open_handler);
            server_data_open(rpc_userptr);
            break;
        case RPC_DATA_CLOSE:
            assert(data_close_handler);
            server_data_close(rpc_userptr);
            break;
        case RPC_DATA_READ:
            assert(data_read_handler);
            server_data_read(rpc_userptr);
            break;
        case RPC_DATA_WRITE:
            assert(data_write_handler);
            server_data_write(rpc_userptr);
            break;
        case RPC_DATA_GETC:
            assert(data_getc_handler);
            server_data_getc(rpc_userptr);
            break;
        case RPC_DATA_PUTC:
            assert(data_putc_handler);
            server_data_putc(rpc_userptr);
            break;
        case RPC_DATA_LSEEK:
            assert(data_lseek_handler);
            server_data_lseek(rpc_userptr);
            break;
        case RPC_DATA_GET_SIZE:
            assert(data_get_size_handler);
            server_data_get_size(rpc_userptr);
            break;
        case RPC_DATA_EXPAND:
            assert(data_expand_handler);
            server_data_expand(rpc_userptr);
            break;
        case RPC_DATA_DATAMAP:
            assert(data_datamap_handler);
            server_data_datamap(rpc_userptr);
            break;
        case RPC_DATA_DATAUNMAP:
            assert(data_dataunmap_handler);
            server_data_dataunmap(rpc_userptr);
            break;
        case RPC_DATA_INIT_DATA:
            assert(data_init_data_handler);
            server_data_init_data(rpc_userptr);
            break;
        case RPC_DATA_HAVE_DATA:
            assert(data_have_data_handler);
            server_data_have_data(rpc_userptr);
            break;
        case RPC_DATA_UNHAVE_DATA:
            assert(data_unhave_data_handler);
            server_data_unhave_data(rpc_userptr);
            break;
        case RPC_DATA_PROVIDE_DATA_FROM_PARAMBUFFER:
            assert(data_provide_data_from_parambuffer_handler);
            server_data_provide_data_from_parambuffer(rpc_userptr);
            break;
        default:
            return -1;
    }
    return 0;
}

