/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

#include <refos-rpc/rpc.h>
#include <refos-rpc/name_client.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>

#include <stdint.h>
#include <stdlib.h>

/*! @file
    @brief Generated file for the name interface. Please do NOT edit this file. */

refos_err_t nsv_register(seL4_CPtr nameserv, char* name, seL4_CPtr ep) {
    int rpc__error_;
    refos_err_t __ret__;
    memset(&__ret__, 0, sizeof(refos_err_t));

    rpc_init("nsv_register", RPC_NSV_REGISTER);
    rpc_set_dest(nameserv);
    rpc_push_str(name);
    rpc_push_cptr(ep);

    rpc__error_ = rpc_call_server();
    if (rpc__error_) {
        rpc_release();
        return __ret__;
    }

    rpc_pop_buf(&__ret__, sizeof(refos_err_t));
    rpc_release();
    return __ret__;
}

refos_err_t nsv_unregister(seL4_CPtr nameserv, char* name) {
    int rpc__error_;
    refos_err_t __ret__;
    memset(&__ret__, 0, sizeof(refos_err_t));

    rpc_init("nsv_unregister", RPC_NSV_UNREGISTER);
    rpc_set_dest(nameserv);
    rpc_push_str(name);

    rpc__error_ = rpc_call_server();
    if (rpc__error_) {
        rpc_release();
        return __ret__;
    }

    rpc_pop_buf(&__ret__, sizeof(refos_err_t));
    rpc_release();
    return __ret__;
}

seL4_CPtr nsv_resolve_segment_internal(seL4_CPtr nameserv, char* path, int* resolvedBytes, refos_err_t* errval) {
    int rpc__error_;
    seL4_CPtr __ret__;
    memset(&__ret__, 0, sizeof(seL4_CPtr));

    rpc_init("nsv_resolve_segment_internal", RPC_NSV_RESOLVE_SEGMENT_INTERNAL);
    rpc_set_dest(nameserv);
    rpc_push_str(path);

    rpc__error_ = rpc_call_server();
    if (rpc__error_) {
        rpc_release();
        return __ret__;
    }

    rpc_pop_buf(resolvedBytes, sizeof(int));
    rpc_pop_buf(errval, sizeof(refos_err_t));
    __ret__ = (seL4_CPtr) rpc_pop_cptr();
    __ret__ = rpc_copyout_cptr(__ret__);
    rpc_release();
    return __ret__;
}


