/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

// DO NOT EDIT MANUALLY!!!
// This file was generated by CIDL - Simple C IDL Compiler.

#include <refos-rpc/rpc.h>
#include <refos-rpc/name_server.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>


int rpc_sv_name_dispatcher(void *rpc_userptr, uint32_t label) {
    switch (label) {
        case RPC_NSV_REGISTER:
            assert(nsv_register_handler);
            server_nsv_register(rpc_userptr);
            break;
        case RPC_NSV_UNREGISTER:
            assert(nsv_unregister_handler);
            server_nsv_unregister(rpc_userptr);
            break;
        case RPC_NSV_RESOLVE_SEGMENT_INTERNAL:
            assert(nsv_resolve_segment_internal_handler);
            server_nsv_resolve_segment_internal(rpc_userptr);
            break;
        default:
            return -1;
    }
    return 0;
}

