/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

#include <refos-rpc/rpc.h>
#include <refos-rpc/name_server.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>

#include <stdint.h>
#include <stdlib.h>

/*! @file
    @brief Generated file for the name interface. Please do NOT edit this file. */

void server_nsv_register(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    char* rpc_name = (char*)rpc_sv_pop_str(rpc_userptr);
    seL4_CPtr rpc_ep = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));

    rpc_sv_track_obj(rpc_userptr, rpc_name);

    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = nsv_register_handler(rpc_userptr, rpc_name, rpc_ep);

    reply_nsv_register(rpc_userptr, *rpc___ret__);
}

void reply_nsv_register(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_nsv_unregister(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    char* rpc_name = (char*)rpc_sv_pop_str(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));

    rpc_sv_track_obj(rpc_userptr, rpc_name);

    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = nsv_unregister_handler(rpc_userptr, rpc_name);

    reply_nsv_unregister(rpc_userptr, *rpc___ret__);
}

void reply_nsv_unregister(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_nsv_resolve_segment_internal(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    char* rpc_path = (char*)rpc_sv_pop_str(rpc_userptr);
    int* rpc_resolvedBytes = rpc_malloc(sizeof(int));
    refos_err_t* rpc_errval = rpc_malloc(sizeof(refos_err_t));
    seL4_CPtr rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_path);
    rpc_sv_track_obj(rpc_userptr, rpc_resolvedBytes);
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = nsv_resolve_segment_internal_handler(rpc_userptr, rpc_path, rpc_resolvedBytes, rpc_errval);

    reply_nsv_resolve_segment_internal(rpc_userptr, rpc_resolvedBytes, rpc_errval, rpc___ret__);
}

void reply_nsv_resolve_segment_internal(void *rpc_userptr, int* rpc_resolvedBytes, refos_err_t* rpc_errval, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_resolvedBytes, sizeof(int));
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(refos_err_t));
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}


