/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

#include <refos-rpc/rpc.h>
#include <refos-rpc/proc_server.h>
#include <refos/refos.h>

#include <stdint.h>
#include <stdlib.h>

/*! @file
    @brief Generated file for the proc interface. Please do NOT edit this file. */

void server_proc_ping(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_ping_handler(rpc_userptr);

    reply_proc_ping(rpc_userptr, *rpc___ret__);
}

void reply_proc_ping(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_new_endpoint_internal(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    refos_err_t* rpc_errval = rpc_malloc(sizeof(refos_err_t));
    seL4_CPtr rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = proc_new_endpoint_internal_handler(rpc_userptr, rpc_errval);

    reply_proc_new_endpoint_internal(rpc_userptr, rpc_errval, rpc___ret__);
}

void reply_proc_new_endpoint_internal(void *rpc_userptr, refos_err_t* rpc_errval, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(refos_err_t));
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_new_async_endpoint_internal(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    refos_err_t* rpc_errval = rpc_malloc(sizeof(refos_err_t));
    seL4_CPtr rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = proc_new_async_endpoint_internal_handler(rpc_userptr, rpc_errval);

    reply_proc_new_async_endpoint_internal(rpc_userptr, rpc_errval, rpc___ret__);
}

void reply_proc_new_async_endpoint_internal(void *rpc_userptr, refos_err_t* rpc_errval, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(refos_err_t));
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_watch_client(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_liveness = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    seL4_CPtr rpc_deathEP = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    int32_t* rpc_deathID = rpc_malloc(sizeof(int32_t));
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));

    rpc_sv_track_obj(rpc_userptr, rpc_deathID);

    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_watch_client_handler(rpc_userptr, rpc_liveness, rpc_deathEP, rpc_deathID);

    reply_proc_watch_client(rpc_userptr, rpc_deathID, *rpc___ret__);
}

void reply_proc_watch_client(void *rpc_userptr, int32_t* rpc_deathID, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_deathID, sizeof(int32_t));
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_unwatch_client(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_liveness = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_unwatch_client_handler(rpc_userptr, rpc_liveness);

    reply_proc_unwatch_client(rpc_userptr, *rpc___ret__);
}

void reply_proc_unwatch_client(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_create_mem_window_internal(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    uint32_t rpc_vaddr = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    uint32_t rpc_size = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    uint32_t rpc_permissions = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    uint32_t rpc_flags = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc_errval = rpc_malloc(sizeof(refos_err_t));
    seL4_CPtr rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = proc_create_mem_window_internal_handler(rpc_userptr, rpc_vaddr, rpc_size, rpc_permissions, rpc_flags, rpc_errval);

    reply_proc_create_mem_window_internal(rpc_userptr, rpc_errval, rpc___ret__);
}

void reply_proc_create_mem_window_internal(void *rpc_userptr, refos_err_t* rpc_errval, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(refos_err_t));
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_resize_mem_window(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_window = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_size = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_resize_mem_window_handler(rpc_userptr, rpc_window, rpc_size);

    reply_proc_resize_mem_window(rpc_userptr, *rpc___ret__);
}

void reply_proc_resize_mem_window(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_delete_mem_window(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_window = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_delete_mem_window_handler(rpc_userptr, rpc_window);

    reply_proc_delete_mem_window(rpc_userptr, *rpc___ret__);
}

void reply_proc_delete_mem_window(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_get_mem_window(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    uint32_t rpc_vaddr = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    seL4_CPtr rpc___ret__ = 0;


    rpc___ret__ = proc_get_mem_window_handler(rpc_userptr, rpc_vaddr);

    reply_proc_get_mem_window(rpc_userptr, rpc___ret__);
}

void reply_proc_get_mem_window(void *rpc_userptr, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_get_mem_window_dspace(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_window = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc_errval = rpc_malloc(sizeof(refos_err_t));
    seL4_CPtr rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = proc_get_mem_window_dspace_handler(rpc_userptr, rpc_window, rpc_errval);

    reply_proc_get_mem_window_dspace(rpc_userptr, rpc_errval, rpc___ret__);
}

void reply_proc_get_mem_window_dspace(void *rpc_userptr, refos_err_t* rpc_errval, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(refos_err_t));
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_register_as_pager(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_window = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    seL4_CPtr rpc_faultNotifyEP = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    seL4_Word* rpc_winID = rpc_malloc(sizeof(seL4_Word));
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));

    rpc_sv_track_obj(rpc_userptr, rpc_winID);

    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_register_as_pager_handler(rpc_userptr, rpc_window, rpc_faultNotifyEP, rpc_winID);

    reply_proc_register_as_pager(rpc_userptr, rpc_winID, *rpc___ret__);
}

void reply_proc_register_as_pager(void *rpc_userptr, seL4_Word* rpc_winID, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_winID, sizeof(seL4_Word));
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_unregister_as_pager(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_window = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_unregister_as_pager_handler(rpc_userptr, rpc_window);

    reply_proc_unregister_as_pager(rpc_userptr, *rpc___ret__);
}

void reply_proc_unregister_as_pager(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_notification_buffer(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dataspace = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_notification_buffer_handler(rpc_userptr, rpc_dataspace);

    reply_proc_notification_buffer(rpc_userptr, *rpc___ret__);
}

void reply_proc_notification_buffer(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_window_map(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_window = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_windowOffset = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    uint32_t rpc_srcAddr = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_window_map_handler(rpc_userptr, rpc_window, rpc_windowOffset, rpc_srcAddr);

    reply_proc_window_map(rpc_userptr, *rpc___ret__);
}

void reply_proc_window_map(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_window_unmap(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_window_unmap_handler(rpc_userptr);

    reply_proc_window_unmap(rpc_userptr, *rpc___ret__);
}

void reply_proc_window_unmap(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_window_getID(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_window = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    int rpc___ret__ = 0;


    rpc___ret__ = proc_window_getID_handler(rpc_userptr, rpc_window);

    reply_proc_window_getID(rpc_userptr, rpc___ret__);
}

void reply_proc_window_getID(void *rpc_userptr, int rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_uint(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_set_parambuffer(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_dataspace = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_size = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_set_parambuffer_handler(rpc_userptr, rpc_dataspace, rpc_size);

    reply_proc_set_parambuffer(rpc_userptr, *rpc___ret__);
}

void reply_proc_set_parambuffer(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_new_proc(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    char* rpc_name = (char*)rpc_sv_pop_str(rpc_userptr);
    char* rpc_params = (char*)rpc_sv_pop_str(rpc_userptr);
    bool* rpc_block = rpc_malloc(sizeof(bool));
    rpc_sv_pop_buf(rpc_userptr, rpc_block, sizeof(bool));
    int32_t rpc_priority = (int32_t)rpc_sv_pop_uint(rpc_userptr);
    int32_t* rpc_status = rpc_malloc(sizeof(int32_t));
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));

    rpc_sv_track_obj(rpc_userptr, rpc_name);
    rpc_sv_track_obj(rpc_userptr, rpc_params);
    rpc_sv_track_obj(rpc_userptr, rpc_block);
    rpc_sv_track_obj(rpc_userptr, rpc_status);

    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_new_proc_handler(rpc_userptr, rpc_name, rpc_params, *rpc_block, rpc_priority, rpc_status);

    reply_proc_new_proc(rpc_userptr, rpc_status, *rpc___ret__);
}

void reply_proc_new_proc(void *rpc_userptr, int32_t* rpc_status, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_status, sizeof(int32_t));
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_exit(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    int32_t rpc_status = (int32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_exit_handler(rpc_userptr, rpc_status);

    reply_proc_exit(rpc_userptr, *rpc___ret__);
}

void reply_proc_exit(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_clone_internal(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_Word* rpc_entryPoint = rpc_malloc(sizeof(seL4_Word));
    rpc_sv_pop_buf(rpc_userptr, rpc_entryPoint, sizeof(seL4_Word));
    seL4_Word* rpc_childStack = rpc_malloc(sizeof(seL4_Word));
    rpc_sv_pop_buf(rpc_userptr, rpc_childStack, sizeof(seL4_Word));
    int rpc_flags = (int)rpc_sv_pop_uint(rpc_userptr);
    seL4_Word* rpc_arg = rpc_malloc(sizeof(seL4_Word));
    rpc_sv_pop_buf(rpc_userptr, rpc_arg, sizeof(seL4_Word));
    refos_err_t* rpc_errval = rpc_malloc(sizeof(refos_err_t));
    int rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_entryPoint);
    rpc_sv_track_obj(rpc_userptr, rpc_childStack);
    rpc_sv_track_obj(rpc_userptr, rpc_arg);
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = proc_clone_internal_handler(rpc_userptr, *rpc_entryPoint, *rpc_childStack, rpc_flags, *rpc_arg, rpc_errval);

    reply_proc_clone_internal(rpc_userptr, rpc_errval, rpc___ret__);
}

void reply_proc_clone_internal(void *rpc_userptr, refos_err_t* rpc_errval, int rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(refos_err_t));
    rpc_sv_push_uint(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_nice(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    int rpc_threadID = (int)rpc_sv_pop_uint(rpc_userptr);
    int rpc_priority = (int)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = proc_nice_handler(rpc_userptr, rpc_threadID, rpc_priority);

    reply_proc_nice(rpc_userptr, *rpc___ret__);
}

void reply_proc_nice(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_proc_get_irq_handler(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    int rpc_irq = (int)rpc_sv_pop_uint(rpc_userptr);
    seL4_CPtr rpc___ret__ = 0;


    rpc___ret__ = proc_get_irq_handler_handler(rpc_userptr, rpc_irq);

    reply_proc_get_irq_handler(rpc_userptr, rpc___ret__);
}

void reply_proc_get_irq_handler(void *rpc_userptr, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}


