/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

// DO NOT EDIT MANUALLY!!!
// This file was generated by CIDL - Simple C IDL Compiler.

#include <refos-rpc/rpc.h>
#include <refos-rpc/proc_server.h>
#include <refos/refos.h>


int rpc_sv_proc_dispatcher(void *rpc_userptr, uint32_t label) {
    switch (label) {
        case RPC_PROC_PING:
            assert(proc_ping_handler);
            server_proc_ping(rpc_userptr);
            break;
        case RPC_PROC_NEW_ENDPOINT_INTERNAL:
            assert(proc_new_endpoint_internal_handler);
            server_proc_new_endpoint_internal(rpc_userptr);
            break;
        case RPC_PROC_NEW_ASYNC_ENDPOINT_INTERNAL:
            assert(proc_new_async_endpoint_internal_handler);
            server_proc_new_async_endpoint_internal(rpc_userptr);
            break;
        case RPC_PROC_WATCH_CLIENT:
            assert(proc_watch_client_handler);
            server_proc_watch_client(rpc_userptr);
            break;
        case RPC_PROC_UNWATCH_CLIENT:
            assert(proc_unwatch_client_handler);
            server_proc_unwatch_client(rpc_userptr);
            break;
        case RPC_PROC_CREATE_MEM_WINDOW_INTERNAL:
            assert(proc_create_mem_window_internal_handler);
            server_proc_create_mem_window_internal(rpc_userptr);
            break;
        case RPC_PROC_RESIZE_MEM_WINDOW:
            assert(proc_resize_mem_window_handler);
            server_proc_resize_mem_window(rpc_userptr);
            break;
        case RPC_PROC_DELETE_MEM_WINDOW:
            assert(proc_delete_mem_window_handler);
            server_proc_delete_mem_window(rpc_userptr);
            break;
        case RPC_PROC_GET_MEM_WINDOW:
            assert(proc_get_mem_window_handler);
            server_proc_get_mem_window(rpc_userptr);
            break;
        case RPC_PROC_GET_MEM_WINDOW_DSPACE:
            assert(proc_get_mem_window_dspace_handler);
            server_proc_get_mem_window_dspace(rpc_userptr);
            break;
        case RPC_PROC_REGISTER_AS_PAGER:
            assert(proc_register_as_pager_handler);
            server_proc_register_as_pager(rpc_userptr);
            break;
        case RPC_PROC_UNREGISTER_AS_PAGER:
            assert(proc_unregister_as_pager_handler);
            server_proc_unregister_as_pager(rpc_userptr);
            break;
        case RPC_PROC_NOTIFICATION_BUFFER:
            assert(proc_notification_buffer_handler);
            server_proc_notification_buffer(rpc_userptr);
            break;
        case RPC_PROC_WINDOW_MAP:
            assert(proc_window_map_handler);
            server_proc_window_map(rpc_userptr);
            break;
        case RPC_PROC_WINDOW_UNMAP:
            assert(proc_window_unmap_handler);
            server_proc_window_unmap(rpc_userptr);
            break;
        case RPC_PROC_WINDOW_GETID:
            assert(proc_window_getID_handler);
            server_proc_window_getID(rpc_userptr);
            break;
        case RPC_PROC_SET_PARAMBUFFER:
            assert(proc_set_parambuffer_handler);
            server_proc_set_parambuffer(rpc_userptr);
            break;
        case RPC_PROC_NEW_PROC:
            assert(proc_new_proc_handler);
            server_proc_new_proc(rpc_userptr);
            break;
        case RPC_PROC_EXIT:
            assert(proc_exit_handler);
            server_proc_exit(rpc_userptr);
            break;
        case RPC_PROC_CLONE_INTERNAL:
            assert(proc_clone_internal_handler);
            server_proc_clone_internal(rpc_userptr);
            break;
        case RPC_PROC_NICE:
            assert(proc_nice_handler);
            server_proc_nice(rpc_userptr);
            break;
        case RPC_PROC_GET_IRQ_HANDLER:
            assert(proc_get_irq_handler_handler);
            server_proc_get_irq_handler(rpc_userptr);
            break;
        default:
            return -1;
    }
    return 0;
}

