/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

#include <refos-rpc/rpc.h>
#include <refos-rpc/serv_server.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>

#include <stdint.h>
#include <stdlib.h>

/*! @file
    @brief Generated file for the serv interface. Please do NOT edit this file. */

void server_serv_connect_direct(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_liveness = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    int* rpc_errval = rpc_malloc(sizeof(int));
    seL4_CPtr rpc___ret__ = 0;
    rpc_sv_track_obj(rpc_userptr, rpc_errval);


    rpc___ret__ = serv_connect_direct_handler(rpc_userptr, rpc_liveness, rpc_errval);

    reply_serv_connect_direct(rpc_userptr, rpc_errval, rpc___ret__);
}

void reply_serv_connect_direct(void *rpc_userptr, int* rpc_errval, seL4_CPtr rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, rpc_errval, sizeof(int));
    rpc_sv_push_cptr(rpc_userptr, rpc___ret__);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_serv_ping(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = serv_ping_handler(rpc_userptr);

    reply_serv_ping(rpc_userptr, *rpc___ret__);
}

void reply_serv_ping(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_serv_set_param_buffer(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);

    seL4_CPtr rpc_parambuffer_dataspace = (seL4_CPtr)rpc_sv_pop_cptr(rpc_userptr);
    uint32_t rpc_parambuffer_size = (uint32_t)rpc_sv_pop_uint(rpc_userptr);
    refos_err_t* rpc___ret__ = rpc_malloc(sizeof(refos_err_t));


    rpc_sv_track_obj(rpc_userptr, rpc___ret__);

    *rpc___ret__ = serv_set_param_buffer_handler(rpc_userptr, rpc_parambuffer_dataspace, rpc_parambuffer_size);

    reply_serv_set_param_buffer(rpc_userptr, *rpc___ret__);
}

void reply_serv_set_param_buffer(void *rpc_userptr, refos_err_t rpc___ret__) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_push_buf(rpc_userptr, &rpc___ret__, sizeof(refos_err_t));
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}

void server_serv_disconnect_direct(void *rpc_userptr) {
    rpc_sv_init(rpc_userptr);




    serv_disconnect_direct_handler(rpc_userptr);

    reply_serv_disconnect_direct(rpc_userptr);
}

void reply_serv_disconnect_direct(void *rpc_userptr) {
    rpc_reset_contents(rpc_userptr);
    rpc_sv_reply(rpc_userptr);
    rpc_sv_free_tracked_objs(rpc_userptr);
    rpc_sv_release(rpc_userptr);
}


