/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

#ifndef _RPC_INTERFACE_NAME_SERVER_H_
#define _RPC_INTERFACE_NAME_SERVER_H_

#include <refos-rpc/rpc.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>


/*! @file
    @brief Generated file for the name interface. Please do NOT edit this file. */

#ifndef _RPC_NAME_LABEL_ENUMS_
#define _RPC_NAME_LABEL_ENUMS_
/*! @brief RPC syscall label enums for name interface. */
enum rpc_name_label_enum {
    RPC_NAME_LABEL_MIN = NAMESERV_METHODS_BASE,
    RPC_NSV_REGISTER,
    RPC_NSV_UNREGISTER,
    RPC_NSV_RESOLVE_SEGMENT_INTERNAL,
    RPC_NAME_LABEL_MAX
};
#endif

void server_nsv_register(void *rpc_userptr);
void reply_nsv_register(void *rpc_userptr, refos_err_t rpc___ret__);
extern refos_err_t nsv_register_handler(void *rpc_userptr , char* rpc_name , seL4_CPtr rpc_ep) __attribute__((weak));

void server_nsv_unregister(void *rpc_userptr);
void reply_nsv_unregister(void *rpc_userptr, refos_err_t rpc___ret__);
extern refos_err_t nsv_unregister_handler(void *rpc_userptr , char* rpc_name) __attribute__((weak));

void server_nsv_resolve_segment_internal(void *rpc_userptr);
void reply_nsv_resolve_segment_internal(void *rpc_userptr, int* rpc_resolvedBytes, refos_err_t* rpc_errval, seL4_CPtr rpc___ret__);
extern seL4_CPtr nsv_resolve_segment_internal_handler(void *rpc_userptr , char* rpc_path , int* rpc_resolvedBytes , refos_err_t* rpc_errval) __attribute__((weak));

#endif /* _RPC_INTERFACE_NAME_SERVER_H_ */

