/* DO NOT EDIT MANUALLY!!!
   This file was generated by CIDL.

   Copyright 2016, Data61
   Commonwealth Scientific and Industrial Research Organisation (CSIRO)
   ABN 41 687 119 230.

   This software may be distributed and modified according to the terms of
   the BSD 2-Clause license. Note that NO WARRANTY is provided.
   See "LICENSE_BSD2.txt" for details.

   @TAG(D61_BSD)
*/

#ifndef _RPC_INTERFACE_SERV_CLIENT_H_
#define _RPC_INTERFACE_SERV_CLIENT_H_

#include <refos-rpc/rpc.h>
#include <refos/refos.h>

#include <refos/vmlayout.h>


/*! @file
    @brief Generated file for the serv interface. Please do NOT edit this file. */

#ifndef _RPC_SERV_LABEL_ENUMS_
#define _RPC_SERV_LABEL_ENUMS_
/*! @brief RPC syscall label enums for serv interface. */
enum rpc_serv_label_enum {
    RPC_SERV_LABEL_MIN = SERV_METHODS_BASE,
    RPC_SERV_CONNECT_DIRECT,
    RPC_SERV_PING,
    RPC_SERV_SET_PARAM_BUFFER,
    RPC_SERV_DISCONNECT_DIRECT,
    RPC_SERV_LABEL_MAX
};
#endif

/*! @brief Connect to a server and establish a session.

   @param serv The anon cap to the server to connect to.
   @param liveness The calling client's liveness cap.
   @return The established connection session capability. */
seL4_CPtr serv_connect_direct(seL4_CPtr serv, seL4_CPtr liveness, int* errval);

/*! @brief Ping the server. Used to easily test that a connection to the server
   is set up correctly, also may be used for keepalive messages.

   @param session The established connection session to send ping along.
   @return REFOS_ESUCCESS if success, refos_error error code otherwise. */
refos_err_t serv_ping(seL4_CPtr session);

/*! @brief Set the parameter buffer for given server.

   Some functions involve large amounts of data transfer, too large and inefficient to be
   transferred over IPC. In this case, we set up a shared buffer in between the server and the
   client.

   Note that the server may or may not support setting internal or external dataspaces as the
   parameter buffer. The user should check with the documentation for the server. An internal
   dataspace here means that the server is itself a dataserver, and setting the server's own
   dataspace as the parameter buffer. External here means that the dataspace being used as the
   parameter buffer here comes from another dataspace server.

   @param session The established connection session to set param buffer for.
   @param parambuffer_dataspace The dataspace to set as param buffer. May be internal or external.
   @param parambuffer_size The size of the parameter buffer to set up.
   @return REFOS_ESUCCESS if success, refos_error error code otherwise. */
refos_err_t serv_set_param_buffer(seL4_CPtr session, seL4_CPtr parambuffer_dataspace, uint32_t parambuffer_size);

/*! @brief Disconnect from a server.
   @param session The established connection session to disconnect. */
void serv_disconnect_direct(seL4_CPtr session);

#endif /* _RPC_INTERFACE_SERV_CLIENT_H_ */

